lindsay-terry/whats-for-dinner

- assets/js/script.js
- index.html
> added modal to HTML

- assets/css/style.css
- index.html
Adjusted spacing and flex properties for grid in section and main elements using Foundation framework grid classes.  Added custom button color class in html and css.
> adjusted spacing for Y-Axis grid. 

- assets/css/style.css
- index.html
Removed unused items on HTML header, identified and removed unused header CSS.
> Cleaned Header Items. Positioned background, removed unnecessary CSS

- assets/js/script.js
Wrote fetch request to get random meal from API URL.
> Wrote fetch request for random meal.

- assets/css/style.css
- assets/js/script.js
- index.html
Added the HTML code for the modal in the "saved recipes" button and added links to everyone's GitHub profiles with icons in the footer.
> added HTML code for modal and github links in footer

- assets/js/script.js
- index.html
Created functions to retrieve drink information based on user input in dropdown menu newly attached to the generate drink button in the HTML.
> created functions to retrieve drink information based on user input 

- assets/js/script.js
Created function to retrieve drink id of clicked on drink.
Created fetch request to retrieve drink information by id and log to console.
> Created function to retrieve drink id of clicked on drink.

- assets/css/style.css
- assets/js/script.js
- index.html
Centered footer and added Hannah's icon for the GitHub link.
> updated footer styling and added icon

- assets/js/script.js
- index.html
Added the close button to the modal and added JavaScript code for adding the recipe instructions to the card on the screen. Also added styling for the card so that the ingredients/measurements and image are displayed inline.
> Completed rendering the card

- assets/js/script.js
- index.html
Set up empty divs in html, and starter functions for local storage.
Wrote get and set functions for meals and drinks.
> Set up empty divs in html, and starter functions for local storage.

- assets/js/script.js
I fixed the issue we were having with the meal cards rendering one after another instead of one at a time. The meal card data should clear out after pressing the "generate a meal" button and render a brand new recipe. I also reorganized my JavaScript code for the render meal cards function so that it is a bit more clean and easier to follow.
> Fixed Rendering Issue for Meal Cards

- assets/js/script.js
Assigned data-attributes to cards in meal and drink card functions.  Assigned data-attribute to drink card button.  Wrote event listener to properly save drink IDs to local storage.  Wrote outline of event listener to save meal cards to local storage.
> created buttons to save drinks and meals to local storage.

- assets/js/script.js
Added comments in Javascript code for meal card to explain what the pieces are doing. Also moved all the lines for appending elements to the same area so the code is cleaner.
> Added JS Comments for Meal Card Code

- assets/js/script.js
Wrote renderDrinkStorage function to render drink cards to modal.
Added function call in event listener to view saved recipes.
> Wrote renderDrinkStorage function to render drink cards to modal.

- assets/js/script.js
- index.html
Added styling for meal cards using JavaScript and Foundation classes. Rearranged elements in the append area so that they are positioned better on the card. Also removed "example" from the modal id.
> Styling for Meal Cards

- assets/js/script.js
- index.html
Added scroll bar for meal card, rounded corners and function for rendering cards to modal. This code still needs to be debugged.
> Added Styling for Meal Card

- assets/js/script.js
- index.html
Adjusted modal for optimal view of both cards.
> Fixed bug with rendering meal cards. 

- assets/js/script.js
Added styling to drink cards to match meal cards.
> Added styling to drink cards to match meal cards.

- assets/js/script.js
- index.html
Changed scrolling classes to work on all screen sizes.  Adjusted modal header to disappear on small screens.  Added catch statements in case of failed fetch request.
> fixed scrolling on small screen issue.  Added catch statements

- assets/js/script.js
Fixed paragraph that shows recipe instructions so that it looks nicer on the card.
> Fixed Recipe Instructions

- README.md
Added basic outline to README, and some content.
Will continue to update.
> Added basic outline to README, and some content.

- assets/css/style.css
- index.html
Fixed the styling on the footer.
> Fixed Footer Styling

- assets/js/script.js
- index.html
Added comments to JavaScript functions and a few comments in HTML.
> JavaScript Comments

- assets/js/script.js
Created functions and event listeners to delete previously saved meal and drink cards from the saved recipe modal.
> Created functions to delete saved meal and drink cards

- assets/js/script.js
Added alt text attribute to meal and drink images.
> Added alt text attribute to meal and drink images.
